/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.app;

import com.example.app.Library.Catalog;
import com.example.app.Library.Book;

public class App {

    public static void main(String[] args) {
        Catalog catalog = new Catalog();
        catalog.TestInitialization();
        catalog.showInfo();

        System.out.println("Books with less than 1000 pages:");
        for (Book book : catalog.getByLessThanPages(1000)) {
            book.showInfo();
        }
    }

}
